name: Build Source2Roblox

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1
      - name: Restore NuGet packages
        run: nuget restore Source2Roblox.sln
      - name: Build
        run: msbuild Source2Roblox.sln /p:Configuration=Release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Source2Roblox
          path: bin/Release/
