name: Build Source2Roblox

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Source2Roblox
        uses: actions/checkout@v4
        with:
          path: Source2Roblox

      - name: Checkout Roblox-File-Format
        uses: actions/checkout@v4
        with:
          repository: MaximumADHD/Roblox-File-Format
          path: Roblox-File-Format

      - name: Checkout ValveKeyValue
        uses: actions/checkout@v4
        with:
          repository: MaximumADHD/ValveKeyValue
          path: ValveKeyValue

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet for Roblox-File-Format
        run: nuget restore Roblox-File-Format/RobloxFileFormat.csproj -SolutionDirectory Roblox-File-Format

      - name: Restore NuGet for Source2Roblox
        run: nuget restore Source2Roblox/Source2Roblox.sln

      - name: Build
        run: msbuild Source2Roblox/Source2Roblox.sln /p:Configuration=Release

      - name: Find RobloxFileFormat dll
        run: dir /s /b Roblox-File-Format\*.dll

      - name: Copy RobloxFileFormat dll
        run: copy Roblox-File-Format\bin\Release\RobloxFileFormat.dll Source2Roblox\bin\Release\

      - name: Copy ValveKeyValue dll
        run: copy ValveKeyValue\ValveKeyValue\ValveKeyValue\bin\Release\ValveKeyValue.dll Source2Roblox\bin\Release\

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Source2Roblox
          path: Source2Roblox/bin/Release/
